# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          build-essential \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev

    - name: Download Python 3.13 source
      run: |
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
        tar -xf Python-3.13.0.tgz
        cd Python-3.13.0

    - name: Build and install Python 3.13
      run: |
        cd Python-3.13.0
        ./configure --enable-optimizations
        make
        sudo make altinstall

    - name: Verify Python version
      run: |
        python3.13 --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest HW1_test.py
