# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          build-essential \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev

    - name: Download Python 3.13.0 Release Candidate 2
      run: |
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0rc2.tgz

    - name: Extract Python 3.13.0rc2
      run: |
        tar -xf Python-3.13.0rc2.tgz

    - name: Build and install Python 3.13.0rc2
      run: |
        cd Python-3.13.0rc2
        ./configure --enable-optimizations
        make
        sudo make altinstall

    - name: Verify Python version
      run: |
        python3.13 --version

    - name: Install dependencies
      run: |
        python3.13 -m pip install --upgrade pip
        python3.13 install -r requirements.txt


    - name: Test with pytest
      run: |
        set -o pipefail
        python3.13 -m pytest "HW1/HW1_test.py" || true
        python3.13 -m pytest "HW2/tests_merge_sort.py" ||true
        echo "Tests completed"

    - name: Run autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py ||true
        echo "Autopep8 Formatting completed" > autopep8.result.txt

    - name: Run pylint
      run: |
        pylint hw2_debugging.py rand.py ||true
        echo "Pylint analysis completed" > pylint_result.txt

    - name: Run radon (Cyclomatic Complexity)
      run: |
        radon cc hw2_debugging.py rand.py || true
        echo "Radon analysis completed" > radon_result.txt

    
    
    - name: Upload lint results
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: |
          autopep8_result.txt
          pylint_result.txt
          radon_result.txt

