name: Python Test

on:
  push:
    Branches:
        -"main"

jobs:
  build:
    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v4
- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.13'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
- name: Test with pytest
  run: |
    pip install pytest pytest-cov
    pytest HW1_test.py 
#doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
