# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Run pylint
      run: |
        cd HW2
        pylint hw2_debugging.py rand.py ||true
        echo "Pylint analysis completed"
    
    - name: Test with pytest
      run: |
          set -o pipefail
          python3.13 -m pytest "HW2/tests_merge_sort.py"
    

