# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Radon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run radon (Cyclomatic Complexity)
      run: |
        cd HW2
        radon cc hw2_debugging.py rand.py || true
        echo "Radon analysis completed" 

    
    
    - name: Test with pytest
      run: |
          set -o pipefail
          python3.13 -m pytest "HW2/tests_merge_sort.py"
